//! Parallax wallpaper authoring: bake the user's parameters into our depth-parallax
//! shader and write a complete, playable wallpaper package (photo + depth map +
//! shader + manifest) that the existing engine renders like any other wallpaper.

use std::path::Path;

use image::{GrayImage, ImageBuffer, Luma};

/// Tunable look of a parallax creation. These map 1:1 to the shader's baked
/// `const`s; the Parallax Studio sliders drive them.
#[derive(Clone, Copy, Debug)]
pub struct ParallaxParams {
    /// Parallax strength (max UV displacement). DepthFlow's "height".
    pub height: f32,
    /// Zoom-in factor that hides edge gaps created by displacement (>= 1.0).
    pub zoom: f32,
    /// Fixed-point refinement iterations (quality vs cost) — a handful is plenty.
    pub steps: u32,
}

impl Default for ParallaxParams {
    fn default() -> Self {
        // Conservative defaults: gentle depth. Strong displacement on a noisy depth
        // map smears/folds badly (and reveals more disocclusion than the inpaint fill
        // covers), so users dial it up from a calm baseline.
        Self { height: 0.06, zoom: 1.06, steps: 10 }
    }
}

impl ParallaxParams {
    fn sanitized(&self) -> Self {
        Self {
            height: self.height.clamp(0.0, 1.0),
            zoom: self.zoom.clamp(1.0, 2.0),
            steps: self.steps.clamp(8, 256),
        }
    }
}

/// Full GLSL for a parallax creation: the baked parameter constants followed by
/// the shared shader body.
pub fn parallax_shader(params: &ParallaxParams) -> String {
    let p = params.sanitized();
    format!(
        "// Auto-generated by Strata Parallax Studio — parameters baked below.\n\
         const float HEIGHT = {:.4};\n\
         const float ZOOM   = {:.4};\n\
         const int   STEPS  = {};\n\n{}",
        p.height, p.zoom, p.steps,
        include_str!("resources/parallax_body.glsl"),
    )
}

/// Like [`parallax_shader`] but for the layered (LDI) path: foreground over an
/// inpainted background (iChannel0 fg, iChannel1 depth [R = scene depth, G =
/// background depth], iChannel2 bg, iChannel3 subject matte).
///
/// Parameters for the layered (LDI) subject displacement. `subject_depth` is the rigid
/// anchor; `bg_factor` scales the background velocity (1.0 = locked to fg); `damp` is the
/// max per-pixel depth contribution (0 = rigid plane); `max_delta` caps any part's depth
/// deviation from the anchor (anti-smear); `feet_y`/`head_y` (texture-space Y of the
/// subject's contact band and top) drive the anchor-weighted damp ramp.
#[derive(Clone, Copy, Debug)]
pub struct LayeredStyle {
    pub subject_depth: f32,
    pub bg_factor: f32,
    pub damp: f32,
    pub max_delta: f32,
    pub feet_y: f32,
    pub head_y: f32,
}

pub fn parallax_shader_layered(params: &ParallaxParams, s: LayeredStyle) -> String {
    let p = params.sanitized();
    format!(
        "// Auto-generated by Strata Parallax Studio (layered) — parameters baked below.\n\
         const float HEIGHT = {:.4};\n\
         const float ZOOM   = {:.4};\n\
         const int   STEPS  = {};\n\
         const float SUBJECT_DEPTH = {:.4};\n\
         const float BG_FACTOR = {:.4};\n\
         const float DAMP = {:.4};\n\
         const float MAX_DELTA = {:.4};\n\
         const float FEET_Y = {:.4};\n\
         const float HEAD_Y = {:.4};\n\n{}",
        p.height, p.zoom, p.steps,
        s.subject_depth.clamp(0.0, 1.0), s.bg_factor.clamp(0.1, 1.0), s.damp.clamp(0.0, 1.0),
        s.max_delta.clamp(0.01, 1.0), s.feet_y.clamp(0.0, 1.0), s.head_y.clamp(0.0, 1.0),
        include_str!("resources/parallax_layered_body.glsl"),
    )
}

/// Write just the manifest for a package whose assets (image.glsl + PNGs) already
/// exist in `out_dir`. `layered` selects 4-channel bindings (image, depth, background,
/// mask) vs the single-layer 2-channel bindings.
pub fn write_manifest(out_dir: &Path, name: &str, author: &str, layered: bool) -> Result<(), String> {
    let bindings = if layered {
        "    { channel = 0, type = \"texture\", path = \"image.png\" },\n\
         \x20   { channel = 1, type = \"texture\", path = \"depth.png\" },\n\
         \x20   { channel = 2, type = \"texture\", path = \"background.png\" },\n\
         \x20   { channel = 3, type = \"texture\", path = \"mask.png\" },\n"
    } else {
        "    { channel = 0, type = \"texture\", path = \"image.png\" },\n\
         \x20   { channel = 1, type = \"texture\", path = \"depth.png\" },\n"
    };
    let tags = if layered { "[\"Parallax\", \"3D\", \"Cinematic\"]" } else { "[\"Parallax\", \"3D\", \"Depth\"]" };
    let manifest = format!(
        "[wallpaper]\n\
         name = {name:?}\n\
         author = {author:?}\n\
         version = \"1.0.0\"\n\
         tags = {tags}\n\
         passes = [\"image\"]\n\n\
         [render_targets.image]\n\
         source = \"image.glsl\"\n\
         bindings = [\n{bindings}]\n",
    );
    std::fs::write(out_dir.join("manifest.toml"), manifest).map_err(|e| format!("write manifest.toml: {e}"))?;
    Ok(())
}

/// Write a single-layer parallax package (image.png, depth.png, shader, manifest).
pub fn export_wallpaper(
    out_dir: &Path,
    name: &str,
    author: &str,
    source_image: &Path,
    depth: &GrayImage,
    params: &ParallaxParams,
) -> Result<(), String> {
    std::fs::create_dir_all(out_dir).map_err(|e| format!("create {:?}: {e}", out_dir))?;
    image::open(source_image)
        .map_err(|e| format!("open photo {:?}: {e}", source_image))?
        .to_rgb8()
        .save(out_dir.join("image.png"))
        .map_err(|e| format!("write image.png: {e}"))?;
    depth.save(out_dir.join("depth.png")).map_err(|e| format!("write depth.png: {e}"))?;
    std::fs::write(out_dir.join("image.glsl"), parallax_shader(params))
        .map_err(|e| format!("write image.glsl: {e}"))?;
    write_manifest(out_dir, name, author, false)
}

/// Mean of `depth` over the pixels where `mask` is "on" (>128) — the subject's mean
/// depth (0..1). Anchors the free-floating Billboard style.
fn mean_depth_in_mask(depth: &GrayImage, mask: &GrayImage) -> f32 {
    let (mut sum, mut cnt) = (0u64, 0u64);
    for (d, m) in depth.pixels().zip(mask.pixels()) {
        if m.0[0] > 128 {
            sum += d.0[0] as u64;
            cnt += 1;
        }
    }
    if cnt == 0 { 0.7 } else { (sum as f32 / cnt as f32) / 255.0 }
}

/// Mean depth over the BOTTOM band of the subject (where it meets the ground) — its
/// ground-contact depth (0..1). Anchoring the rigid subject here makes it shift at the
/// same rate as the ground it stands on, so it stays planted (the Coherent 3-D style).
fn contact_depth_in_mask(depth: &GrayImage, mask: &GrayImage) -> f32 {
    let (w, h) = mask.dimensions();
    // Vertical extent of the subject.
    let (mut min_y, mut max_y) = (None::<u32>, 0u32);
    for y in 0..h {
        for x in 0..w {
            if mask.get_pixel(x, y).0[0] > 128 {
                min_y.get_or_insert(y);
                max_y = y;
            }
        }
    }
    let Some(min_y) = min_y else { return 0.7 };
    // Bottom 12% of the subject's height is its contact band with the ground.
    let band = ((max_y - min_y) as f32 * 0.12) as u32;
    let band_top = max_y.saturating_sub(band);
    let (mut sum, mut cnt) = (0u64, 0u64);
    for y in band_top..=max_y {
        for x in 0..w {
            if mask.get_pixel(x, y).0[0] > 128 {
                sum += depth.get_pixel(x, y).0[0] as u64;
                cnt += 1;
            }
        }
    }
    if cnt == 0 { mean_depth_in_mask(depth, mask) } else { (sum as f32 / cnt as f32) / 255.0 }
}

/// Texture-space Y (v = row/height, 0 = top … 1 = bottom) of the subject's contact band
/// (lowest "on" row) and its top, for the anchor-weighted damp ramp. Returns (feet, head).
fn mask_band_y(mask: &GrayImage) -> (f32, f32) {
    let (w, h) = mask.dimensions();
    let (mut min_y, mut max_y) = (None::<u32>, 0u32);
    for y in 0..h {
        for x in 0..w {
            if mask.get_pixel(x, y).0[0] > 128 {
                min_y.get_or_insert(y);
                max_y = y;
            }
        }
    }
    let min_y = min_y.unwrap_or(0);
    (max_y as f32 / h as f32, min_y as f32 / h as f32) // (feet, head); v = y/h, bottom = larger
}

/// Separable max-filter (grayscale dilation) by radius `r`. Grows bright (near) regions
/// outward — used to push the subject's interior depth over its antialiased silhouette so
/// the foreground doesn't sample subject/background-averaged edge depth (which would warp
/// into a halo). Operates at a downscaled grid for speed, then upscales.
fn dilate_near(depth: &GrayImage, r: u32) -> GrayImage {
    if r == 0 { return depth.clone(); }
    let (w, h) = (depth.width() as i32, depth.height() as i32);
    let r = r as i32;
    let at = |buf: &GrayImage, x: i32, y: i32| buf.get_pixel(x.clamp(0, w - 1) as u32, y.clamp(0, h - 1) as u32).0[0];
    let mut horiz: GrayImage = ImageBuffer::new(depth.width(), depth.height());
    for y in 0..h {
        for x in 0..w {
            let mut m = 0u8;
            for dx in -r..=r { m = m.max(at(depth, x + dx, y)); }
            horiz.put_pixel(x as u32, y as u32, Luma([m]));
        }
    }
    let mut out: GrayImage = ImageBuffer::new(depth.width(), depth.height());
    for y in 0..h {
        for x in 0..w {
            let mut m = 0u8;
            for dy in -r..=r { m = m.max(horiz.get_pixel(x as u32, (y + dy).clamp(0, h - 1) as u32).0[0]); }
            out.put_pixel(x as u32, y as u32, Luma([m]));
        }
    }
    out
}

/// Write a layered (LDI) parallax package: image.png + depth.png (R = scene depth,
/// G = background-filled depth) + background.png (inpainted) + mask.png (subject
/// matte, its own texture) + the layered shader + 4-binding manifest.
///
/// The matte stays a separate texture so future work can add more of them (per-subject
/// `mask2.png`, …) for multi-layer scenes. depth.png's blue/alpha channels are left
/// free as headroom for that expansion.
pub fn export_layered_wallpaper(
    out_dir: &Path,
    name: &str,
    author: &str,
    source_image: &Path,
    depth: &GrayImage,
    bg_depth: &GrayImage,
    background: &image::RgbImage,
    mask: &GrayImage,
    params: &ParallaxParams,
    billboard: bool,
) -> Result<(), String> {
    std::fs::create_dir_all(out_dir).map_err(|e| format!("create {:?}: {e}", out_dir))?;
    image::open(source_image)
        .map_err(|e| format!("open photo {:?}: {e}", source_image))?
        .to_rgb8()
        .save(out_dir.join("image.png"))
        .map_err(|e| format!("write image.png: {e}"))?;

    // Pack depth.png: R = foreground (scene) depth, G = background-filled depth (B/A
    // reserved). bg_depth is resized to the depth grid so the channels align.
    let (w, h) = depth.dimensions();
    let bg_depth = if bg_depth.dimensions() == (w, h) {
        bg_depth.clone()
    } else {
        image::imageops::resize(bg_depth, w, h, image::imageops::FilterType::Triangle)
    };
    // Foreground depth (R): extend the subject's interior depth over its antialiased
    // silhouette (a few-px dilation of near depth) so the damped foreground never samples
    // subject/background-averaged edge depth → crisp silhouette, no halo warp. R stays
    // SHARP (the subject must read crisply).
    let fg_depth = dilate_near(depth, (w.max(h) / 256).max(2));
    // Background depth (G): lightly smoothed. The background parallaxes per-pixel, and a
    // steeply-receding surface (a road) shears its painted markings under that warp; a
    // gentle blur softens the gradient so the lines flex smoothly instead of distorting,
    // while keeping the coarse near/far structure (distant scenery still parallaxes).
    let bg_depth = image::imageops::blur(&bg_depth, (w.max(h) as f32 / 160.0).max(2.0));
    let mut packed = image::RgbImage::new(w, h);
    for (p, (d, g)) in packed.pixels_mut().zip(fg_depth.pixels().zip(bg_depth.pixels())) {
        p.0 = [d.0[0], g.0[0], 0];
    }
    packed.save(out_dir.join("depth.png")).map_err(|e| format!("write depth.png: {e}"))?;
    background.save(out_dir.join("background.png")).map_err(|e| format!("write background.png: {e}"))?;
    mask.save(out_dir.join("mask.png")).map_err(|e| format!("write mask.png: {e}"))?;

    // Subject anchor + background velocity + damping:
    //   • Coherent 3-D — anchor at the GROUND-CONTACT depth (sampled from the same bg
    //     depth the trail uses) + bg_factor 1.0 so the feet lock to the ground, plus an
    //     anchor-weighted damp (rigid at the feet, up to 0.30 at the head) so tall
    //     subjects read with depth without the full per-pixel shear. MAX_DELTA caps any
    //     part's deviation (a raised arm/gun can't smear).
    //   • Billboard — anchor at MEAN depth, bg lags (0.7), damp 0 (rigid float).
    let (feet_y, head_y) = mask_band_y(mask);
    let style = if billboard {
        LayeredStyle { subject_depth: mean_depth_in_mask(depth, mask), bg_factor: 0.7, damp: 0.0, max_delta: 0.15, feet_y, head_y }
    } else {
        LayeredStyle { subject_depth: contact_depth_in_mask(&bg_depth, mask), bg_factor: 1.0, damp: 0.30, max_delta: 0.15, feet_y, head_y }
    };
    std::fs::write(out_dir.join("image.glsl"), parallax_shader_layered(params, style))
        .map_err(|e| format!("write image.glsl: {e}"))?;
    write_manifest(out_dir, name, author, true)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn shader_bakes_params_and_includes_body() {
        let s = parallax_shader(&ParallaxParams { height: 0.25, zoom: 1.1, steps: 64 });
        assert!(s.contains("const float HEIGHT = 0.2500;"));
        assert!(s.contains("const int   STEPS  = 64;"));
        assert!(s.contains("void mainImage")); // body included
    }

    #[test]
    fn params_are_clamped() {
        let s = parallax_shader(&ParallaxParams { height: 9.0, zoom: 0.1, steps: 1 });
        assert!(s.contains("const float HEIGHT = 1.0000;"));
        assert!(s.contains("const float ZOOM   = 1.0000;"));
        assert!(s.contains("const int   STEPS  = 8;"));
    }
}
